ui:
  container:
    tag: div
    css_class: 'container'

  grid:
    tag: div
    css_class: 'grid'

  row:
    tag: div
    css_class: 'row'
    ui: false

  column:
    tag: div
    css_class: 'wide column'
    ui: false

  div:
    tag: div
    css_class: ''
    ui: false


  # base items
  header:
    tag: div
    css_class: 'header'

  h1:
    tag: h1
    css_class: 'header'

  h2:
    tag: h2
    css_class: 'header'

  h3:
    tag: h3
    css_class: 'header'

  h4:
    tag: h4
    css_class: 'header'

  h5:
    tag: h5
    css_class: 'header'

  h6:
    tag: h6
    css_class: 'header'


  text:
    tag: p
    css_class: 'text'
    ui: false

  icon:
    tag: i
    css_class: 'icon'
    ui: false

  table:
    tag: table
    css_class: table

  divider:
    tag: div
    css_class: 'divider'

  buttons:
    tag: div
    css_class: 'buttons'

  dropdown:
    tag: div
    css_class: 'dropdown'

  menu:
    tag: div
    css_class: 'menu'
    ui: false

  list:
    tag: div
    css_class: 'list'

  message:
    tag: div
    css_class: 'message'

  checkbox:
    tag: div
    css_class: 'checkbox'

  image:
    tag: div
    css_class: 'image'

  meta:
    tag: div
    css_class: 'meta'
    ui: false

  content:
    tag: div
    css_class: 'content'
    ui: false

  description:
    tag: div
    css_class: 'description'
    ui: false

  extra:
    tag: div
    css_class: 'extra'
    ui: false

  segments:
    tag: div
    css_class: 'segments'

  segment:
    tag: div
    css_class: 'segment'

  items:
    tag: div
    css_class: 'items'

  item:
    tag: div
    css_class: 'item'
    ui: false

  cards:
    tag: div
    css_class: 'cards'

  card:
    tag: div
    css_class: 'card'

  feed:
    tag: div
    css_class: 'feed'

  event:
    tag: div
    css_class: 'event'
    ui: false

  date:
    tag: div
    css_class: 'date'
    ui: false

  statistics:
    tag: div
    css_class: 'statistics'

  statistic:
    tag: div
    css_class: 'statistic'
    ui: false

  loader:
    tag: div
    css_class: 'loader'

  label:
    tag: div
    css_class: 'label'

  ribbon:
    tag: div
    css_class: 'ribbon label'


  # core classes used by the internal css framework
  page:
    tag: div
    css_class: page
    ui: false

  fragment:
    tag: div
    css_class: fragment
    ui: false

  component:
    tag: div
    css_class: 'component'
    ui: false

  widget:
    tag: div
    css_class: 'widget'
    ui: false

  element:
    tag: div
    css_class: 'element'
    ui: false

  # forms
  form:
    tag: form
    css_class: 'form'

  field:
    tag: div
    css_class: 'input'

  hidden:
    tag: input
    css_class: ''
    type: 'hidden'
    ui: false

  textarea:
    tag: textarea
    css_class: 'textarea'

  button:
    tag: button
    css_class: 'button'

  # non semantic ui components
  wrapper:
    tag: div
    css_class: 'wrapper'
    ui: false

  figure:
    tag: figure
    css_class: ''
    ui: false


  overlay:
    tag: div
    css_class: 'overlay'
    ui: false

  title:
    tag: div
    css_class: 'title'
    ui: false

  summary:
    tag: div
    css_class: 'summary'
    ui: false

  color:
    tag: span
    css_class: 'color'
    ui: false

  separator:
    tag: div
    css_class: 'separator'
    ui: false

  dynamic:
    tag: div
    css_class: 'dynamic'
    ui: false

  left:
    tag: div
    css_class: 'left'

  right:
    tag: div
    css_class: 'right'

  mobile:
    tag: div
    css_class: 'mobile'
    ui: false

  desktop:
    tag: div
    css_class: 'desktop'
    ui: false
